name: test-clang-format

on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        exclude: './doc ./case ./scripts'
        extensions: 'h,cpp'
        clangFormatVersion: 12
        style: chromium